import type { CapabilityAction, CapabilityDomain, PlatformCapability } from "./types.js";

const capabilities: PlatformCapability[] = [
  {
    domain: "customers",
    action: "search",
    kind: "read",
    toolName: "search_customers",
    description: "Search customers by name, legal name, tax id, email, or phone.",
    optionalFields: ["query"],
  },
  {
    domain: "customers",
    action: "detail",
    kind: "read",
    toolName: "get_customer_details",
    description: "Get full CRM details for one customer.",
    requiredFields: ["customerId"],
  },
  {
    domain: "customers",
    action: "create",
    kind: "write",
    toolName: "create_customer",
    description: "Create a customer record.",
    requiredFields: ["legalName"],
    optionalFields: ["displayName", "taxId", "phone", "email", "address", "city", "department", "notes", "segmentId", "assignedToUserId"],
    requiresConfirmation: true,
  },
  {
    domain: "customers",
    action: "update",
    kind: "write",
    toolName: "update_customer",
    description: "Update an existing customer record.",
    requiredFields: ["customerId"],
    optionalFields: ["legalName", "displayName", "taxId", "phone", "email", "address", "city", "department", "notes", "segmentId", "assignedToUserId"],
    requiresConfirmation: true,
  },
  {
    domain: "contacts",
    action: "search",
    kind: "read",
    toolName: "search_contacts",
    description: "Search contacts by name, role, email, or phone.",
    optionalFields: ["query", "customerId"],
  },
  {
    domain: "contacts",
    action: "create",
    kind: "write",
    toolName: "create_contact",
    description: "Create a contact for a customer.",
    requiredFields: ["customerId", "fullName"],
    optionalFields: ["roleTitle", "phone", "email", "isPrimary", "notes"],
    requiresConfirmation: true,
  },
  {
    domain: "contacts",
    action: "update",
    kind: "write",
    toolName: "update_contact",
    description: "Update an existing contact.",
    requiredFields: ["contactId"],
    optionalFields: ["customerId", "fullName", "roleTitle", "phone", "email", "isPrimary", "notes"],
    requiresConfirmation: true,
  },
  {
    domain: "opportunities",
    action: "search",
    kind: "read",
    toolName: "search_opportunities",
    description: "Search commercial opportunities.",
    optionalFields: ["query", "customerId"],
  },
  {
    domain: "opportunities",
    action: "detail",
    kind: "read",
    toolName: "get_opportunity_details",
    description: "Get details for one opportunity.",
    requiredFields: ["opportunityId"],
  },
  {
    domain: "opportunities",
    action: "create",
    kind: "write",
    toolName: "create_opportunity",
    description: "Create a commercial opportunity for a customer.",
    requiredFields: ["customerId", "title", "stage"],
    optionalFields: ["estimatedValue", "expectedCloseDate"],
    requiresConfirmation: true,
  },
  {
    domain: "opportunities",
    action: "update",
    kind: "write",
    toolName: "update_opportunity",
    description: "Update an opportunity.",
    requiredFields: ["opportunityId"],
    optionalFields: ["title", "stage", "estimatedValue", "expectedCloseDate", "customerId"],
    requiresConfirmation: true,
  },
  {
    domain: "visits",
    action: "search",
    kind: "read",
    toolName: "search_visits",
    description: "Search scheduled or completed visits.",
    optionalFields: ["query", "customerId", "from", "to"],
  },
  {
    domain: "visits",
    action: "create",
    kind: "write",
    toolName: "create_visit",
    description: "Create a scheduled visit.",
    requiredFields: ["customerId", "scheduledAt"],
    optionalFields: ["opportunityId", "summary", "notes"],
    requiresConfirmation: true,
  },
  {
    domain: "visits",
    action: "update",
    kind: "write",
    toolName: "update_visit",
    description: "Update a visit.",
    requiredFields: ["visitId"],
    optionalFields: ["customerId", "opportunityId", "scheduledAt", "summary", "notes"],
    requiresConfirmation: true,
  },
  {
    domain: "visits",
    action: "cancel",
    kind: "write",
    toolName: "update_visit",
    description: "Cancel a scheduled visit.",
    requiredFields: ["visitId"],
    optionalFields: ["reason", "notes"],
    requiresConfirmation: true,
  },
  {
    domain: "visits",
    action: "complete",
    kind: "write",
    toolName: "update_visit",
    description: "Mark a visit as completed.",
    requiredFields: ["visitId"],
    optionalFields: ["notes"],
    requiresConfirmation: true,
  },
  {
    domain: "followups",
    action: "search",
    kind: "read",
    toolName: "search_followups",
    description: "Search follow-up tasks.",
    optionalFields: ["query", "customerId", "opportunityId", "from", "to"],
  },
  {
    domain: "followups",
    action: "create",
    kind: "write",
    toolName: "create_followup",
    description: "Create a follow-up task.",
    requiredFields: ["customerId", "title", "dueAt", "type"],
    optionalFields: ["opportunityId"],
    requiresConfirmation: true,
  },
  {
    domain: "followups",
    action: "update",
    kind: "write",
    toolName: "update_followup",
    description: "Update a follow-up task.",
    requiredFields: ["followupId"],
    optionalFields: ["title", "dueAt", "notes"],
    requiresConfirmation: true,
  },
  {
    domain: "followups",
    action: "cancel",
    kind: "write",
    toolName: "update_followup",
    description: "Cancel a follow-up task.",
    requiredFields: ["followupId"],
    optionalFields: ["notes"],
    requiresConfirmation: true,
  },
  {
    domain: "followups",
    action: "complete",
    kind: "write",
    toolName: "update_followup",
    description: "Mark a follow-up task as completed.",
    requiredFields: ["followupId"],
    optionalFields: ["notes"],
    requiresConfirmation: true,
  },
  {
    domain: "quotes",
    action: "search",
    kind: "read",
    toolName: "search_quotes",
    description: "Search quotes.",
    optionalFields: ["query", "customerId", "opportunityId"],
  },
  {
    domain: "quotes",
    action: "detail",
    kind: "read",
    toolName: "get_quote_details",
    description: "Get quote details.",
    requiredFields: ["quoteId"],
  },
  {
    domain: "quotes",
    action: "create",
    kind: "write",
    toolName: "create_quote",
    description: "Create a quote.",
    requiredFields: ["customerId", "items", "pricing", "conditions", "status"],
    optionalFields: ["opportunityId", "validUntil", "notes"],
    requiresConfirmation: true,
  },
  {
    domain: "quotes",
    action: "update",
    kind: "write",
    toolName: "update_quote",
    description: "Update a quote.",
    requiredFields: ["quoteId"],
    optionalFields: ["status"],
    requiresConfirmation: true,
  },
  {
    domain: "quotes",
    action: "cancel",
    kind: "write",
    toolName: "update_quote",
    description: "Cancel a quote.",
    requiredFields: ["quoteId"],
    optionalFields: ["notes", "status"],
    requiresConfirmation: true,
  },
  {
    domain: "orders",
    action: "search",
    kind: "read",
    toolName: "search_orders",
    description: "Search orders.",
    optionalFields: ["query", "customerId", "opportunityId"],
  },
  {
    domain: "orders",
    action: "detail",
    kind: "read",
    toolName: "get_order_details",
    description: "Get order details.",
    requiredFields: ["orderId"],
  },
  {
    domain: "orders",
    action: "create",
    kind: "write",
    toolName: "create_order",
    description: "Create an order.",
    requiredFields: ["customerId", "items", "pricing", "conditions", "status"],
    optionalFields: ["opportunityId", "sourceQuoteId", "notes"],
    requiresConfirmation: true,
  },
  {
    domain: "orders",
    action: "update",
    kind: "write",
    toolName: "update_order",
    description: "Update an order.",
    requiredFields: ["orderId"],
    optionalFields: ["status"],
    requiresConfirmation: true,
  },
  {
    domain: "orders",
    action: "cancel",
    kind: "write",
    toolName: "update_order",
    description: "Cancel an order.",
    requiredFields: ["orderId"],
    optionalFields: ["notes", "status"],
    requiresConfirmation: true,
  },
  {
    domain: "products",
    action: "search",
    kind: "read",
    toolName: "search_products",
    description: "Search products.",
    optionalFields: ["query"],
  },
  {
    domain: "products",
    action: "detail",
    kind: "read",
    toolName: "get_product_details",
    description: "Get product details.",
    requiredFields: ["productId"],
  },
  {
    domain: "products",
    action: "create",
    kind: "write",
    toolName: "create_product",
    description: "Create a product.",
    requiredFields: ["sku", "name"],
    optionalFields: ["description", "unit", "presentation", "basePrice"],
    requiresConfirmation: true,
  },
  {
    domain: "products",
    action: "update",
    kind: "write",
    toolName: "update_product",
    description: "Update a product.",
    requiredFields: ["productId"],
    optionalFields: ["sku", "name", "description", "unit", "presentation", "basePrice"],
    requiresConfirmation: true,
  },
  {
    domain: "segments",
    action: "search",
    kind: "read",
    toolName: "search_segments",
    description: "Search customer segments.",
    optionalFields: ["query"],
  },
  {
    domain: "segments",
    action: "create",
    kind: "write",
    toolName: "create_segment",
    description: "Create a customer segment.",
    requiredFields: ["name"],
    optionalFields: ["description"],
    requiresConfirmation: true,
  },
  {
    domain: "segments",
    action: "update",
    kind: "write",
    toolName: "update_segment",
    description: "Update a customer segment.",
    requiredFields: ["segmentId"],
    optionalFields: ["name", "description"],
    requiresConfirmation: true,
  },
  {
    domain: "dashboard",
    action: "detail",
    kind: "read",
    toolName: "get_dashboard_summary",
    description: "Get the CRM dashboard summary.",
  },
];

function cloneCapability(capability: PlatformCapability): PlatformCapability {
  return {
    ...capability,
    requiredFields: capability.requiredFields ? [...capability.requiredFields] : undefined,
    optionalFields: capability.optionalFields ? [...capability.optionalFields] : undefined,
  };
}

export function listCapabilities(): PlatformCapability[] {
  return capabilities.map(cloneCapability);
}

export function getCapability(domain: CapabilityDomain, action: CapabilityAction): PlatformCapability | undefined {
  const capability = capabilities.find((cap) => cap.domain === domain && cap.action === action);
  return capability ? cloneCapability(capability) : undefined;
}

export function capabilitiesForPrompt(): string {
  return capabilities
    .map((capability) => {
      const required = capability.requiredFields?.length ? ` required: ${capability.requiredFields.join(", ")}` : "";
      const confirmation = capability.requiresConfirmation ? " confirmation required" : "";
      return `- ${capability.domain}.${capability.action} (${capability.kind}) -> ${capability.toolName}.${required}${confirmation}`;
    })
    .join("\n");
}
